### ISSUE TITLE
Command line not parsed correctly

### ISSUE THREAD

**Issue by jgallimore** [tomitribe/sheldon#12]
I'm unable to submit parameter values with spaces in:

crest> venue update --id=6 --name="My Test"
Excess arguments: Test"

Usage: update [options]

Options: 
  --capacity=<Integer>  
  --city=<String>  
  --country=<String>  
  --description=<String>  
  --id=<Long>  
  --name=<String>  
  --street=<String>  
  --url=<String>  
crest> 

And 

crest> venue update --id=6 "--name=My Test"
Excess arguments: "--name=My, Test"

Usage: update [options]

Options: 
  --capacity=<Integer>  
  --city=<String>  
  --country=<String>  
  --description=<String>  
  --id=<Long>  
  --name=<String>  
  --street=<String>  
  --url=<String>  
crest>

**Comment by dblevins** [comment]
Fixed in Sheldon 0.8
