### ISSUE TITLE
sheldone-corejava-commands

### ISSUE THREAD

**Issue by dblevins** [tomitribe/sheldon#25]
Features could be on `java.lang.Runtime` and similar object:
- do a gc
- display memory
- report processor data
- list threads (`Set<Thread> threadSet = Thread.getAllStackTraces().keySet();`)
- manipulate system properties

Fancier commands could email thread dumps.

**Comment by danielsoro** [comment]
fixed with https://github.com/tomitribe/sheldon/pull/30
