### ISSUE TITLE
Rename project to crest-connector

### ISSUE THREAD

**Issue by dblevins** [tomitribe/sheldon#9]
Definitely `telnet-connector` no longer fits.  Maybe `crest-connector` ?

**Comment by danielsoro** [comment]
:+1:

**Comment by danielsoro** [comment]
Hey @dblevins this issue is fixed. Can you close it!?

**Comment by tomitribe-dev** [comment]
Closed :)

**Comment by danielsoro** [comment]
Thanks @jgallimore  :D
